/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManoMachineSimulatorView.java
 *
 * Created on 2009-5-1, 23:25:42
 */

package manomachine;

import manomachine.logic.CodeParser;

/**
 *
 * @author Administrator
 */
public class ManoMachineSimulatorView extends javax.swing.JDialog {

    private String[] instructions;
    int sc;
    int currentPosition;
    /** Creates new form ManoMachineSimulatorView */
    public ManoMachineSimulatorView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        stepButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        SC = new javax.swing.JTextField();
        AC = new javax.swing.JTextField();
        DR = new javax.swing.JTextField();
        IR = new javax.swing.JTextField();
        TR = new javax.swing.JTextField();
        AR = new javax.swing.JTextField();
        PC = new javax.swing.JTextField();
        INPR = new javax.swing.JTextField();
        OUTR = new javax.swing.JTextField();
        I = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        E = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(manomachine.ManoMachineApp.class).getContext().getResourceMap(ManoMachineSimulatorView.class);
        stepButton.setText(resourceMap.getString("stepButton.text")); // NOI18N
        stepButton.setName("stepButton"); // NOI18N
        stepButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stepButtonMouseClicked(evt);
            }
        });

        jTextField1.setFont(resourceMap.getFont("jTextField1.font")); // NOI18N
        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jTextField2.setFont(resourceMap.getFont("jTextField2.font")); // NOI18N
        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        SC.setText(resourceMap.getString("SC.text")); // NOI18N
        SC.setName("SC"); // NOI18N

        AC.setText(resourceMap.getString("AC.text")); // NOI18N
        AC.setName("AC"); // NOI18N

        DR.setText(resourceMap.getString("DR.text")); // NOI18N
        DR.setName("DR"); // NOI18N

        IR.setText(resourceMap.getString("IR.text")); // NOI18N
        IR.setName("IR"); // NOI18N

        TR.setText(resourceMap.getString("TR.text")); // NOI18N
        TR.setName("TR"); // NOI18N

        AR.setText(resourceMap.getString("AR.text")); // NOI18N
        AR.setName("AR"); // NOI18N

        PC.setText(resourceMap.getString("PC.text")); // NOI18N
        PC.setName("PC"); // NOI18N

        INPR.setText(resourceMap.getString("INPR.text")); // NOI18N
        INPR.setName("INPR"); // NOI18N

        OUTR.setText(resourceMap.getString("OUTR.text")); // NOI18N
        OUTR.setName("OUTR"); // NOI18N
        OUTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OUTRActionPerformed(evt);
            }
        });

        I.setText(resourceMap.getString("I.text")); // NOI18N
        I.setName("I"); // NOI18N

        jTextField13.setText(resourceMap.getString("jTextField13.text")); // NOI18N
        jTextField13.setName("jTextField13"); // NOI18N

        E.setText(resourceMap.getString("E.text")); // NOI18N
        E.setName("E"); // NOI18N

        jTextField15.setText(resourceMap.getString("jTextField15.text")); // NOI18N
        jTextField15.setName("jTextField15"); // NOI18N

        jTextField16.setText(resourceMap.getString("jTextField16.text")); // NOI18N
        jTextField16.setName("jTextField16"); // NOI18N

        jTextField17.setText(resourceMap.getString("jTextField17.text")); // NOI18N
        jTextField17.setName("jTextField17"); // NOI18N

        jTextField18.setText(resourceMap.getString("jTextField18.text")); // NOI18N
        jTextField18.setName("jTextField18"); // NOI18N

        jTextField19.setText(resourceMap.getString("jTextField19.text")); // NOI18N
        jTextField19.setName("jTextField19"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jTextField27.setText(resourceMap.getString("jTextField27.text")); // NOI18N
        jTextField27.setName("jTextField27"); // NOI18N

        jTextField28.setText(resourceMap.getString("jTextField28.text")); // NOI18N
        jTextField28.setName("jTextField28"); // NOI18N

        jTextField29.setText(resourceMap.getString("jTextField29.text")); // NOI18N
        jTextField29.setName("jTextField29"); // NOI18N

        jTextField30.setText(resourceMap.getString("jTextField30.text")); // NOI18N
        jTextField30.setName("jTextField30"); // NOI18N

        jTextField31.setText(resourceMap.getString("jTextField31.text")); // NOI18N
        jTextField31.setName("jTextField31"); // NOI18N

        jTextField32.setText(resourceMap.getString("jTextField32.text")); // NOI18N
        jTextField32.setName("jTextField32"); // NOI18N

        jTextField33.setText(resourceMap.getString("jTextField33.text")); // NOI18N
        jTextField33.setName("jTextField33"); // NOI18N

        jTextField34.setText(resourceMap.getString("jTextField34.text")); // NOI18N
        jTextField34.setName("jTextField34"); // NOI18N

        jTextField35.setText(resourceMap.getString("jTextField35.text")); // NOI18N
        jTextField35.setName("jTextField35"); // NOI18N

        startButton.setText(resourceMap.getString("startButton.text")); // NOI18N
        startButton.setName("startButton"); // NOI18N
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        jTextField36.setText(resourceMap.getString("jTextField36.text")); // NOI18N
        jTextField36.setName("jTextField36"); // NOI18N

        jTextField37.setText(resourceMap.getString("jTextField37.text")); // NOI18N
        jTextField37.setName("jTextField37"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField36, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField27, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                        .addComponent(SC, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(I, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(DR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(INPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(OUTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(252, 252, 252))))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OUTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField29)
                            .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AC)
                            .addComponent(TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OUTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OUTRActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_OUTRActionPerformed

    private void stepButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stepButtonMouseClicked
        
        
        if(sc == 0)
        {    
            AR.setText(PC.getText());
            SC.setText(Integer.toBinaryString(sc));
                sc++;
                jTextField19.setText("AR<-PC");
                System.out.println(sc);
        }
        if (sc == 1)
        {
               IR.setText(instructions[currentPosition]);
               PC.setText(Integer.toHexString(Integer.parseInt(deleteZeros(PC.getText()), 16)+1));
                    SC.setText(Integer.toBinaryString(sc));
               sc++;
               jTextField19.setText("IR<-M[AR], PC<-PC+1");
        }
        if( sc == 2)
        {      
              String opr = Integer.toBinaryString(Integer.parseInt(instructions[currentPosition].substring(4,5), 16));  
             opr =  new CodeParser().fillZero(opr);
              AR.setText(Integer.toBinaryString(Integer.parseInt(instructions[currentPosition].substring(5,8), 16)));
              I.setText(opr.substring(0,1));
                   SC.setText(Integer.toBinaryString(sc));
              sc++;
              jTextField19.setText("Decode operation code in IR, AR<IR(1-11), I<-IR()15");
              
              
              
        }
        if (sc == 3)
        {
            String opr = Integer.toBinaryString(Integer.parseInt(instructions[currentPosition].substring(4,5), 16));  
            if (opr.substring(0,1).equals("F") || opr.substring(0,1).equals("7")){
             doRegisterInstructions();
            }
            else {
            doMRInstructions();
            }
        }
        currentPosition++;
        

}//GEN-LAST:event_stepButtonMouseClicked
  private void CLA(){ AC.setText("0000000000000000");
              
             SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Clear AC");}
 private void CLE(){
      E.setText("0");
       SC.setText(Integer.toBinaryString(sc));
        jTextField19.setText("Clear E");
  }
 
 private void CMA()
 {
      char[]  AC = SC.getText().toCharArray();
      for (char c : AC)
      {
           if (c == '1')
                   c = 0;
           else 
               c = 1;
      }
      this.AC.setText(new String(AC));
      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Complement AC");
             
 
 }
 private void CME()
 {
     char[] e = E.getText().toCharArray();
     for (char c : e)
      {
           if (c == '1')
                   c = 0;
           else 
               c = 1;
      }
     
      E.setText(new String(e));
      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Complement E");
 }
 
 private void CIR()
 {
    String e = E.getText();
    String AC = this.AC.getText();
    AC = e.concat(AC);
    e = AC .substring(16,17);
    AC = AC.substring(0,16);
    E.setText(e);
            this.AC.setText(AC);

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Circulate right AC and E");

 }
 private void CIL(){

    String e = E.getText();
    String AC = this.AC.getText();
    AC = AC.concat(e);
    e = AC.substring(0,1);
    AC = AC.substring(1,17);

    E.setText(e);
            this.AC.setText(AC);

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Circulate left AC and E");

 }
 private void INC()
 {
    int AC = Integer.parseInt(this.AC.getText(), 2);
    AC++;
    this.AC.setText(Integer.toBinaryString(AC));

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Increment AC");
 }
 private void SPA()
 {
    int AC = Integer.parseInt(this.AC.getText(), 2);
    if (AC >0)
    {
       int PC  = Integer.parseInt(this.PC.getText(), 2);
       PC ++ ;
       this.PC.setText(Integer.toBinaryString(PC));
       currentPosition++;

    }

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Skip next instruction if AC positive");
 }

 private void SNA()
 {
 int AC = Integer.parseInt(this.AC.getText(), 2);
    if (AC <0)
    {
       int PC  = Integer.parseInt(this.PC.getText(), 2);
       PC ++ ;
       this.PC.setText(Integer.toBinaryString(PC));
       currentPosition++;

    }

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Skip next instruction if AC negative");
  }

 private void SZA()
 {
     int AC = Integer.parseInt(this.AC.getText(), 2);
    if (AC == 0)
    {
       int PC  = Integer.parseInt(this.PC.getText(), 2);
       PC ++ ;
       this.PC.setText(Integer.toBinaryString(PC));
       currentPosition++;

    }

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Skip next instruction if AC zero");
 }

 private void SZE()
 {
    int e = Integer.parseInt(E.getText(), 2);
    if (e == 0)
    {
       int PC  = Integer.parseInt(this.PC.getText(), 2);
       PC ++ ;
       this.PC.setText(Integer.toBinaryString(PC));
       currentPosition++;

    }

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Skip next instruction if E zero");
 }

 private void HLT()
         {

      SC.setText(Integer.toBinaryString(sc));
             jTextField19.setText("Halt computer");

 stepButton.removeMouseListener(  new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stepButtonMouseClicked(evt);
            }
        });
 }
    private void doRegisterInstructions() 
    {
          int instruction = Integer.parseInt(instructions[currentPosition].substring(4,8),16);
          if (instruction== 0x7800){
              CLA();} 
          if (instruction == 0x7400)
          {
          CLE();
          }
          else if (instruction == 0x7200)
          {
            CMA();
          }
          else if (instruction == 0x7100)
          {
             CME();
          }
          else  if (instruction == 0x7080)
          {
            CIR();}
          else if (instruction == 0x7040)
          {
           CIL();
          }
          else if (instruction == 0x7020)
          {
           INC();
          }
          else  if (instruction == 0x7010)
          {
            SPA();
          }
          else if (instruction == 0x7008)
          {
            SNA();
          }
          else if (instruction == 0x7004)
          {
             SZA();
          }
          else if (instruction == 0x7002)
          {
             SZE();
          }
          else if (instruction == 0x7001)
          {
              HLT();
          }
          else if (instruction >= 0xF040 && instruction <= 0xF800 )
          {
              System.out.print("I/0 function is under development");
          }
          else{
          System.out.println("Error in doing register instructions");
          }
    }
    private void doMRInstructions()
    {
        
    }
    
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
       
         String codes = jTextArea1.getText();
          instructions = codes.split("\n");
         SC.setText("000");
         String pcInitial = instructions[0].substring(0, 3);
         PC.setText(adjustToTwelve(Integer.toBinaryString(Integer.parseInt(pcInitial, 16))));
         currentPosition = 0;
         
        
        
        
        
}//GEN-LAST:event_startButtonMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManoMachineSimulatorView dialog = new ManoMachineSimulatorView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private String adjustToTwelve(String s)
    {

        String ss= s;
        for (int i = 0; i < 12-s.length(); i ++)
        {ss= "0".concat(ss);}


        return ss;


    }
    private String deleteZeros(String s)
    {
       String ss = "";
       for(Character c : s.toCharArray())
       {
          if (c !='0'){
            ss=  ss.concat(c.toString());
          }
          
       }
       return ss;
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AC;
    private javax.swing.JTextField AR;
    private javax.swing.JTextField DR;
    private javax.swing.JTextField E;
    private javax.swing.JTextField I;
    private javax.swing.JTextField INPR;
    private javax.swing.JTextField IR;
    private javax.swing.JTextField OUTR;
    private javax.swing.JTextField PC;
    private javax.swing.JTextField SC;
    private javax.swing.JTextField TR;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stepButton;
    // End of variables declaration//GEN-END:variables

}
